# #+INCLUDE: "../../headers.org"
#+TITLE: Rapport comparaison de DLS, BFS et IDS
#+AUTHOR: Lucien Cartier-Tilet et Sacha Hu
#+DATE: 2018:09:27
#+EMAIL: phundrak@phundrak.fr sacha.hu@hotmail.fr
#+DESCRIPTION: Rapport sur les comparaisons d’algorithmes de calcul de la suite de fibonacci
#+LANGUAGE: fr
#+LATEX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{xltxtra,fontspec,xunicode}\usepackage[total={6.5in,9.5in}]{geometry}\setromanfont[Numbers=Lowercase]{Charis SIL}
#+LATEX_HEADER: \usepackage{xcolor} \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{colorlinks=true,linkbordercolor=red,linkcolor=blue,pdfborderstyle={/S/U/W 1}}
#+OPTIONS: toc:nil |:nil

Il nous a été demandé d’implémenter et de comparer trois algorithmes de recherche de solution pour le jeu du taquin. Ainsi, nous avons implémenté DLS, BFS et IDS en Rust afin de pouvoir comparer leur temps d’exécution. Le code source peut être trouvé en ligne à l’adresse suivante : [[https://github.com/Phundrak/comparaison-algo-recherche-ia]]

Suivant la profondeur maximale de recherche donnée aux algorithmes, les résultats peuvent varier, mais nous avons remarqué que l’algorithme DLS seul donne souvent un résultat plus lentement que IDS qui lui-même est plus lent que BFS. En effet, à titre d’exemple, nous avons pour résultat une solution à 79 coups trouvée en 229ms environ avec DLS seul, une solution en 18 coups trouvée en 31ms environ avec IDS et une solution en 16 coups trouvée en 17ms environ lorsque le code est compilé en release et est exécuté sur un Intel i7-6700HQ (3.5GHz).

Il semblerait que l’algorithme BFS soit l’algorithme optimal afin de trouver rapidement une solution efficace au jeu du taquin comparé aux deux autres algorithmes. Il est en tout cas clair que la solution de l’algorithme DLS seul est très peu efficace et est proposée beaucoup trop lentement.
